### ISSUE TITLE
Executor failed with the below error (#8 ERROR: executor failed running [/bin/sh -c dotnet publish "LogShark/LogShark.csproj" -r linux-x64 --self-contained false -c Release /p:Version=4.2.3 -o out]: exit code: 1)

### ISSUE THREAD

**Issue by vinay4191** [dylanwijman/logshark#1]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/121208647/209044173-c427ec54-dc7b-457d-9782-fda2f847cae8.png">

**Comment by dylanwijman** [comment]
This error has been introduced due to the latest release of Logshark.
Besides the error, the RUN scripts still seemed to produce valid outputs.
The setup files now use Logsharks' previous version (4.2.2) to prevent this error from occurring.

Let's continue the discussion here: https://github.com/tableau/Logshark/issues/165

**Comment by vinay4191** [comment]
Thanks Dylan

**Comment by KarthikINV** [comment]
Is this issues resolved or still in discussion, I'm getting same error for publish and run as well
